name: "Create release branch"

on:
  workflow_dispatch:
    inputs:
      release-name:
        description: "Release name"
        required: true
        type: string

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Identify as bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Apply version bump (major)
        run: npm version major

      - name: Git push version bump
        run: git push --follow-tags

      - name: Create, checkout and push release branch
        run: |
          git branch release/${{ inputs.release-name }}
          git checkout release/${{ inputs.release-name }}
          git push -u origin release/${{ inputs.release-name }}

      - name: Output version change
        run: echo "Current version $(npm pkg get version)"
